library(rgl)
library(car)
library(shiny)

#######################################################################################
###                                      NOTES                                      ###
#######################################################################################
##This code is written to take in the generated pCOA weighted unifrac values and generate
##a pCOA plot using the top three values. It will also allow users to upload a labels 
##document, which will allow for additional visualization of categorical labels.

#######################################################################################
###                                      Code                                      ###
#######################################################################################

function(input,output){
  
  # Takes the input file generated by user, and reads the table 
  data <- reactive({
      file <- input$file
      if (is.null(file))
        return(NULL)
      pcoa_full <- read.table(file=input$file$datapath)
  })
  
  datafull <- reactive({
    file2 <- input$file2
    if (is.null(file2))
      return(NULL)
    pcoa_labs <- read.table(file=input$file2$datapath)
  })  
  
    #Display the summary for the file information provided by the user
    output$filepcoa <- renderTable({
      if(is.null(data())){return ()}
      input$file
    })
    
    # Displays a preview of the data to ensure table is in correct format
    output$tablepcoa <- renderTable({
      if(is.null(data())){return ()}
      data()
    })
    
    # Prints the summary and data preview back to the user
    output$tb <- renderUI({
      if(is.null(data())){return()}
      else
        tabsetPanel(tabPanel("File Summary", tableOutput("filepcoa")), tabPanel("Data", tableOutput("tablepcoa")))
  })

  #When the active button has been selected, generates a pCOA plot for the user to manipulate
    observeEvent(input$goButton, {
      
      #Create palette of colors
      palette(c(brewer.pal(n=12, name = "Set3"),brewer.pal(n=12, name = "Paired"),brewer.pal(n=11, name = "Spectral")))
      
      #Assign top three pCOA values to plot
      pc1 <- data()[,2]
      pc2 <- data()[,3]
      pc3 <- data()[,4]
      
      #Assign labels to the plot, from input
      pcoa_labs <- datafull()
      
      output$plot <- renderRglwidget({
        open3d(useNULL=TRUE)
        scatter3d(x=pc1, y=pc2, z=pc3, surface=FALSE, groups = pcoa_labs$V5, pch=5, surface.col = palette(), cex=5,
                  labels = pcoa_labs$V5, id.n=nrow(pcoa_labs), axis.col = c("white", "white", "white"), bg="black")
        par3d(mouseMode = "trackball")
        rglwidget()
      })
    })
}