library(rgl)
library(car)
library(shiny)

#######################################################################################
###                                      NOTES                                      ###
#######################################################################################
##This code is written to take in the generated pCOA weighted unifrac values and generate
##a pCOA plot using the top three values. It will also allow users to upload a labels 
##document, which will allow for additional visualization of categorical labels.

#######################################################################################
###                                      Code                                      ###
#######################################################################################

function(input,output){
  
  # Takes the input file generated by user, and reads the table 
  data <- reactive({
    file <- input$file
    if (is.null(file))
      return(NULL)
    pcoa_full <- read.table(file=input$file$datapath)
    return (pcoa_full)
  })

  #Display the summary for the file information provided by the user
  output$filedf <- renderTable({
    if(is.null(data())){return ()}
    input$file
  })
    
  # Displays a preview of the data to ensure table is in correct format
  output$table <- renderTable({
    if(is.null(data())){return ()}
    data()
  })
    
  # Prints the summary and data preview back to the user
  output$tb <- renderUI({
    if(is.null(data())){return()}
    else
      tabsetPanel(tabPanel("File Summary", tableOutput("filedf")), tabPanel("Data", tableOutput("table")))
  })
 
  #When the active button has been selected, generates a pCOA plot for the user to manipulate
  observeEvent(input$goButton, {
    
    #Assign colors for the categories
    colors <- c("red", "green", "white", "yellow")
    
    #Assign top three pCOA values to plot
    pc1 <- data()[,2]
    pc2 <- data()[,3]
    pc3 <- data()[,4]
     
    output$plot <- renderRglwidget({
      open3d(useNULL=TRUE)
      scatter3d(x=pc1, y=pc2, z=pc3, surface=FALSE, pch=15, surface.col = colors, cex=10,
                axis.col = c("white", "white", "white"), bg="black")
      par3d(mouseMode = "trackball")
      rglwidget()
    })
  })
}